include:
   - redis.yaml
#   - celery.yaml
services:
  # Data Store Images
  exoctk:
    build:
      context: ..
      dockerfile: ./docker/exoctk/Dockerfile
      args:
        - exoctk_version=patch_celery
        - python_version=3.11
        - exoctk_data=$EXOCTK_DATA
        - has_exo=$HAS_EXO
        - exoctk_repo=exoctk/exoctk
        - dev_source=clone
    entrypoint: /exoctk/exoctk_entrypoint.sh
    volumes:
      - exoctk_data:/exoctk/exoctk_data
      - shared_data:/exoctk/data
    ports:
      - "5000:5000"
    restart: unless-stopped
  pandexo:
    build:
      context: ./pandexo
      dockerfile: Dockerfile
      args:
        - pandexo_branch=dhs
        - pandexo_version=3.0.0
        - python_version=3.11
        - pandeia_version=2025.7
        - has_exo=$HAS_EXO
        - has_pandeia=$HAS_PANDEIA
        - has_syn=$HAS_SYN
    volumes:
      - exoctk_data:/data/exoctk
      - pandeia_data:/data/pandeia
      - synphot_data:/data/trds
    ports:
      - "1111:1111"
    restart: unless-stopped
  worker:
    build:
      context: ..
      dockerfile: ./docker/exoctk/Dockerfile
      args:
        - exoctk_version=patch_celery
        - python_version=3.11
        - exoctk_data=$EXOCTK_DATA
        - has_exo=$HAS_EXO
        - exoctk_repo=exoctk/exoctk
        - dev_source=clone
    entrypoint: /exoctk/worker_entrypoint.sh
    volumes:
      - exoctk_data:/exoctk/exoctk_data
      - shared_data:/exoctk/data
    depends_on:
      - redis
      - exoctk
    deploy:
      replicas: 5
    restart: unless-stopped
volumes:
  exoctk_data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: $EXOCTK_DATA
  pandeia_data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: $pandeia_refdata
  synphot_data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: $PYSYN_CDBS
  shared_data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: $EXO_TMP
