name: exoctk-3.10
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy>=5.3.1
  - bokeh>=3.2.2
  - cython>=0.29.35
  - docopt>=0.6.2
  - docutils>=0.16
  - flake8>=6.0.0
  - flask>=2.2.2
  - ipython>=8.12.0
  - jupyter>=1.0.0
  - matplotlib>=3.7.1
  - numpydoc>=1.5.0
  - pandas>=2.0.3
  - paramiko>=2.8.1
  - pip>=23.1.2
  - pytest>=7.3.1
  - python=3.10.11
  - pyyaml>=6.0.0
  - scp>=0.14.1
  - sphinx>=5.0.2
  - sqlalchemy>=1.4.39
  - wtforms>=2.3.3
  - pip:
    - asteval>=0.9.31
    - awscli>=1.29.4
    - bandit>=1.7.5
    - batman-package>=2.4.8
    - bibtexparser>=1.4.0
    - boto3>=1.28.5
    - corner>=2.2.2
    - docutils>=0.16
    - flask_wtf>=1.1.1
    - h5py>=3.9.0
    - gunicorn>=21.1.0
    - numpy>=1.25.1
    - platon>=5.4
    - pyerfa>=2.0.0
    - pysiaf>=0.20.0
    - pysynphot>=2.0.0
    - pyvo>=1.4.1
    - regions>=0.7
    - scipy>=1.11.1
    - sphinx_astropy>=1.9.1
    - svo-filters>=0.4.4
    - werkzeug>=3.0.1
    - jwst_gtvt>=1.0.0
    - astroquery>=0.4.6
