name: exoctk-3.5
channels:
  - defaults
  - http://ssb.stsci.edu/astroconda
dependencies:
  - astropy=3.0.4
  - bokeh=0.13.0
  - cython=0.28.5
  - docopt=0.6.2
  - docutils=0.14
  - flake8=3.7.7
  - flask=1.1.1
  - gunicorn=19.9.0
  - h5py=2.8.0
  - ipython=6.5.0
  - matplotlib=3.0.0
  - numba=0.39.0
  - numpy=1.15.2
  - numpydoc=0.9.1
  - pandas=0.23.4
  - paramiko=1.18.4
  - pytest=3.8.1
  - python=3.5.6
  - pyyaml=3.13
  - scipy=1.1.0
  - scp=0.13.2
  - sphinx=2.1.2
  - sqlalchemy=1.2
  - wtforms=2.2.1
  - pip:
    - asteval==0.9.13
    - astroquery==0.3.8
    - awscli==1.16.210
    - bandit==1.6.2
    - batman-package==2.4.6
    - bibtexparser==1.1.0
    - corner==2.0.1
    - flask_wtf==0.14.2
    - lmfit==0.9.13
    - platon==4.0
    - pysynphot==0.9.12
    - sphinx_astropy==1.1.1
    - sphinx-automodapi==0.11
    - svo-filters==0.2.19
    - git+https://github.com/spacetelescope/jwst_gtvt.git
