name: exoctk-3.5
channels:
  - defaults
  - http://ssb.stsci.edu/astroconda
dependencies:
  - astropy=3.0.4
  - bokeh=0.13.0
  - boto3=1.9.82
  - cython=0.28.5
  - docopt=0.6.2
  - docutils=0.14
  - flake8=3.5.0
  - flask=1.1.2
  - gunicorn=19.9.0
  - h5py=2.8.0
  - ipython=6.5.0
  - jupyter=1.0.0
  - matplotlib=3.0.0
  - numba=0.39.0
  - numpy=1.14.2
  - numpydoc=0.9.2
  - pandas=0.22.0
  - paramiko=1.18.4
  - python=3.5.6
  - pyyaml=3.13
  - scipy=1.1.0
  - scp=0.13.2
  - sphinx=3.0.3
  - sqlalchemy=1.2.11
  - wtforms=2.3.1
  - pip:
    - asteval==0.9.18
    - astroquery==0.3.10
    - awscli
    - bandit==1.6.2
    - batman-package==2.4.6
    - bibtexparser==1.1.0
    - corner==2.0.1
    - flask_wtf==0.14.3
    - lmfit==0.9.15
    - platon==5.1.1
    - pysynphot==0.9.14
    - pytest==4.6
    - sphinx_astropy==1.3
    - sphinx-automodapi==0.12
    - svo-filters==0.2.19
    - werkzeug==0.16.1
    - git+https://github.com/spacetelescope/jwst_gtvt.git@cd6bc76f66f478eafbcc71834d3e735c73e03ed5
