name: exoctk-3.5
channels:
  - defaults
  - http://ssb.stsci.edu/astroconda
dependencies:
  - alabaster=0.7.11
  - asn1crypto=0.24.0
  - astropy=3.0.4
  - astroquery
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - babel=2.6.0
  - blas=1.0
  - bokeh=0.13.0
  - ca-certificates
  - certifi=2018.8.24
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - cryptography=2.3.1
  - cycler=0.10.0
  - cython=0.28.5
  - docopt=0.6.2
  - docutils=0.14
  - flask=1.0.2
  - freetype=2.9.1
  - h5py=2.8.0
  - hdf5=1.10.2
  - idna=2.7
  - imagesize=1.1.0
  - intel-openmp=2019.1
  - ipython=6.5.0
  - itsdangerous=0.24
  - jinja2=2.10
  - jpeg=9b
  - jupyter=1.0.0
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libopenblas=0.3.3
  - libpng=1.6.35
  - libtiff=4.0.9
  - llvmlite=0.24.0
  - markupsafe=1.0
  - matplotlib=3.0.0
  - mkl=2019.1
  - mkl_random=1.0.1
  - mock=2.0.0
  - more-itertools=4.3.0
  - ncurses=6.1
  - numba=0.39.0
  - numpy=1.15.2
  - numpy-base=1.15.2
  - numpydoc=0.8.0
  - olefile=0.46
  - openssl=1.0.2p
  - packaging=17.1
  - pandas=0.23.4
  - pathlib2=2.3.2
  - pbr=4.2.0
  - pillow=5.2.0
  - pip=10.0.1
  - pluggy=0.7.1
  - psutil=5.4.7
  - py=1.6.0
  - pycparser=2.19
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.1
  - pysocks=1.6.8
  - pytest=3.8.1
  - pytest-arraydiff=0.2
  - pytest-astropy=0.4.0
  - pytest-doctestplus=0.1.3
  - pytest-openfiles=0.3.0
  - pytest-remotedata=0.3.0
  - python=3.5.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pyyaml=3.13
  - readline=7.0
  - requests=2.19.1
  - scipy=1.1.0
  - setuptools=40.2.0
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sphinx=1.7.9
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - sqlalchemy=1.2
  - sqlite=3.25.3
  - tk=8.6.8
  - tornado=5.1.1
  - urllib3=1.23
  - werkzeug=0.14.1
  - wheel=0.31.1
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - asteval==0.9.13
    - astroquery==0.3.8
    - batman-package==2.4.6
    - beautifulsoup4==4.6.3
    - bibtexparser==1.0.1
    - corner==2.0.1
    - entrypoints==0.2.3
    - Flask==1.0.2
    - flask_wtf==0.14.2
    - future==0.17.1
    - html5lib==1.0.1
    - keyring==17.0.0
    - lmfit==0.9.12
    - platon==3.1
    - pytest==3.8.1
    - svo-filters==0.2.19
    - uncertainties==3.0.3
    - webencodings==0.5.1
    - wtforms==2.2.1
    - git+https://github.com/spacetelescope/jwst_gtvt.git
