name: ExoCTK CI

on: [pull_request]

jobs:

  ExoCTK-CI:

    name: Python - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: ./env/environment-${{ matrix.python-version }}.yml
          cache-env: true
          cache-downloads: true

      - run: |

          echo "Setting useful environment variables:"
          echo " "
          export PYTHONVERSION=${{ matrix.python-version }}
          echo "PYTHONVERSION: $PYTHONVERSION"
          export EXOCTK_DATA=$RUNNER_WORKSPACE/exoctk/exoctk/data/
          echo $EXOCTK_DATA

          echo " "
          echo "Installing exoctk conda environment"
          echo " "
          cd $RUNNER_WORKSPACE/
          cd exoctk/
          $CONDA/bin/conda env update -f env/environment-${{ matrix.python-version }}.yml -n exoctk-${{ matrix.python-version }}
          $CONDA/bin/conda env export

      - run: pip install .

      - run: pytest exoctk/tests/